// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	env: [
		{
			name:  "DEVICE_IP"
			value: "192.168.68.112"
		},
	]
}
