// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	env: [{
		name: "DATA_SOURCE_NAME"
		value: "oracle://user:password@myhost:1521/service"
	}]
}
