name: Run dagger on tagged commits

on:
  push:
    branches:
      - master
    tags:
      - '*@v*.*.*'

permissions:
  contents: read # needed for checkout

jobs:
  pushModule:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Call dagger on-push
      uses: dagger/dagger-for-github@v7
      with:
        verb: call
        args: publish-module-from-tag --dir=. --tag=${{ github.ref }} --password=${{ secrets.GITHUB_TOKEN }}
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  buildDagger:
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - uses: actions/checkout@v4

    - name: Run simple dagger command on Dependabot commit
      uses: dagger/dagger-for-github@v7
      with:
        verb: functions
        cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
