name: Publish on commit

on:
  push:
    tags: ["*"] # semver format

permissions:
  contents: read # needed for checkout

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Timoni
      uses: stefanprodan/timoni/actions/setup@main
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: |
        timoni mod push ./cron \
          oci://docker.io/anthonymbrice/cron \
          --version ${{ github.ref_name }}
          --latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
          -a 'org.opencontainers.image.description=A Timoni module for `cron`.'
    - name: Pull
      run: |
        mkdir -p /tmp/cron
        timoni mod pull oci://docker.io/anthonymbrice/cron \
          --version ${{ github.ref_name }} \
          --output /tmp/cron
