name: Publish on tag

on:
  push:
    branches:
      - master

permissions:
  contents: read # needed for checkout

jobs:
  runDagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: extract-metadata
      uses: stdlib-js/metadata-action@v2

    - name: Call dagger onPush
      run: |
        echo 'json: ${{ steps.extract-metadata.outputs.metadata }}'
      # cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      # dagger call on-push --dir=. --commit-json=
      # uses: dagger/dagger-for-github@v5
      # with:
      #   version: "0.10.2"
      #   verb: call
      #   module: github.com/anthonybrice/timpkg@3ea4fac61cb0a744e9e279658b049e2c49d7257a
      #   args: on-push --dir=. --commit-json=${{ steps.metadata.outputs.commit }}
      #   # args: node dagger/src/index.ts
