name: Publish on tag

on:
  push:
    branches:
      - master

permissions:
  contents: read # needed for checkout

jobs:
  runDagger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Call dagger on-push
      uses: dagger/dagger-for-github@v5
      with:
        version: "0.10.2"
        verb: call
        args: on-push --dir=./modules --token=${{ secrets.GITHUB_TOKEN }}
