name: Publish on tag

on:
  push:
    branches:
      - master

permissions:
  contents: read # needed for checkout

jobs:
  runDagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ $GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_SECRET }}

    - name: Call dagger on-push
      uses: dagger/dagger-for-github@v5
      with:
        version: "0.10.2"
        verb: call
        args: on-push --dir=./modules
