name: Publish on tag

on:
  push:
    tags:
    - "cron/*" # semver format
    - "hedgedoc/*" # semver format

permissions:
  contents: read # needed for checkout

jobs:
  push_cron:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/cron/')
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract Version
      id: set_version
      run: echo "::set-output name=version::$(echo ${{ github.ref }} | cut -d '/' -f2)"
    - name: Setup Timoni
      uses: stefanprodan/timoni/actions/setup@main
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: |
        timoni mod push ./modules/cron \
          oci://docker.io/anthonymbrice/cron \
          --version ${{ steps.set_version.outputs.version }} \
          --latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
          -a 'org.opencontainers.image.description=A Timoni module for `cron`.'
    - name: Pull
      run: |
        mkdir -p /tmp/cron
        timoni mod pull oci://anthonymbrice/cron \
          --version ${{ steps.set_version.outputs.version }} \
          --output /tmp/cron

  push_hedgedoc:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/hedgedoc/')
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract Version
      id: set_version
      run: echo "::set-output name=version::$(echo ${{ github.ref }} | cut -d '/' -f2)"
    - name: Setup Timoni
      uses: stefanprodan/timoni/actions/setup@main
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: |
        timoni mod push ./modules/hedgedoc \
          oci://docker.io/anthonymbrice/hedgedoc \
          --version ${{ steps.set_version.outputs.version }} \
          --latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
          -a 'org.opencontainers.image.description=A Timoni module for Hedgedoc.'
    - name: Pull
      run: |
        mkdir -p /tmp/hedgedoc
        timoni mod pull oci://anthonymbrice/hedgedoc \
          --version ${{ steps.set_version.outputs.version }} \
          --output /tmp/hedgedoc
